version: '3.3'
services:
  node:
     build:
        context: ./
        args:
          
     entrypoint: run-node "node index.js"
  mysql:
     build:
        context: ./mysql
        args:
            _MYSQL_USER=root 
            -MYSQL_ROOT_PASSWORD=123
     expose:
         - "3306"
  mongo:
     build: ./mongo
     expose:
        - "27017"
  nginx:
      build:
         context: ./nginx
         args:
             -WEB_REVERSE_PROXY_PORT=8000
             -WEB_SSL=false
      ports:
         - "80:80"   
              
